safeArea: {
  flex: 1,
  backgroundColor: '#f0f0f0',
},
scrollView: {
  flexGrow: 1,
},
container: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  padding: 20,
},
loggedInContainer: {
  width: '100%',
  alignItems: 'center',
},
loggedInText: {
  fontSize: 16,
  marginBottom: 20,
  color: '#333',
},
signInButton: {
  backgroundColor: '#4285F4',
  paddingVertical: 12,
  paddingHorizontal: 24,
  borderRadius: 5,
  alignItems: 'center',
},
signOutButton: {
  backgroundColor: '#DB4437',
  paddingVertical: 12,
  paddingHorizontal: 24,
  borderRadius: 5,
  alignItems: 'center',
  marginBottom: 20,
},
buttonText: {
  color: '#ffffff',
  fontSize: 16,
  fontWeight: 'bold',
},
emailContainer: {
  width: '100%',
  backgroundColor: '#ffffff',
  borderRadius: 10,
  padding: 20,
  marginBottom: 20,
  elevation: 3,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 2},
  shadowOpacity: 0.1,
  shadowRadius: 4,
},
emailTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  marginBottom: 10,
  color: '#333',
},
subject: {
  fontSize: 16,
  marginBottom: 20,
  color: '#666',
},
statusContainer: {
  backgroundColor: '#f9f9f9',
  borderRadius: 5,
  padding: 10,
},
status: {
  fontSize: 24,
  fontWeight: 'bold',
  textAlign: 'center',
  marginBottom: 5,
},
scam: {
  color: '#D32F2F',
},
ham: {
  color: '#388E3C',
},
confidence: {
  fontSize: 16,
  textAlign: 'center',
  color: '#666',
},
fetchingText: {
  fontSize: 16,
  color: '#666',
  marginBottom: 20,
},
timerContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  width: '100%',
  backgroundColor: '#ffffff',
  borderRadius: 10,
  padding: 15,
  elevation: 3,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 2},
  shadowOpacity: 0.1,
  shadowRadius: 4,
},
timerText: {
  fontSize: 16,
  color: '#333',
},
refreshButton: {
  backgroundColor: '#4CAF50',
  borderRadius: 5,
  padding: 10,
},